name              'configer'
maintainer        'Mr. T'
maintainer_email  'me@example.com'
license           'MIT'
description       'Sandbox recipes'
version           '1.0.0'
supports          'ubuntu'
